name: ble_proximity_signal_ios
description: iOS implementation of the ble_proximity_signal plugin
version: 0.1.0+1
homepage: https://github.com/AndrewDongminYoo/ble_proximity_signal
repository: https://github.com/AndrewDongminYoo/ble_proximity_signal
issue_tracker: https://github.com/AndrewDongminYoo/ble_proximity_signal/issues
topics:
  - bluetooth
  - ble
  - proximity
  - rssi
  - beacon

environment:
  sdk: ^3.9.0

resolution: workspace

flutter:
  plugin:
    implements: ble_proximity_signal
    platforms:
      ios:
        pluginClass: BleProximitySignalPlugin
        dartPluginClass: BleProximitySignalIOS

dependencies:
  ble_proximity_signal_platform_interface: ^0.1.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0
